import type { RegionConfig } from './types';

export const africaConfig: RegionConfig = {
  id: 'africa',
  name: 'Africa',
  shortName: 'AF',
  description: 'Tailored for African universities — NUC/AAU-aligned, mobile-money-ready, multilingual.',
  flagEmoji: '🌍',
  countries: ['Nigeria', 'Kenya', 'South Africa', 'Ghana', 'Egypt', 'Ethiopia', 'Senegal', 'Tanzania', 'Uganda', 'Rwanda'],
  defaultLocale: 'en',
  supportedLocales: ['en', 'fr', 'ar', 'sw', 'yo', 'ha', 'am', 'pt'],
  rtl: false,
  defaultCurrency: 'NGN',
  currencies: ['NGN', 'KES', 'ZAR', 'GHS', 'EGP', 'XOF', 'ETB', 'TZS', 'UGX', 'RWF'],
  defaultTimezone: 'Africa/Lagos',
  dateFormat: 'DD/MM/YYYY',
  numberFormat: 'en-NG',
  nameOrder: 'given-family',
  gpaScaleMax: 5.0,
  gradeScale: [
    { minScore: 70, maxScore: 100, grade: 'A', gradePoint: 5.0, remark: 'Excellent' },
    { minScore: 60, maxScore: 69, grade: 'B', gradePoint: 4.0, remark: 'Very Good' },
    { minScore: 50, maxScore: 59, grade: 'C', gradePoint: 3.0, remark: 'Good' },
    { minScore: 45, maxScore: 49, grade: 'D', gradePoint: 2.0, remark: 'Fair' },
    { minScore: 40, maxScore: 44, grade: 'E', gradePoint: 1.0, remark: 'Pass' },
    { minScore: 0, maxScore: 39, grade: 'F', gradePoint: 0.0, remark: 'Fail' },
  ],
  classification: [
    { minCgpa: 4.50, label: 'First Class Honours', shortLabel: '1st Class' },
    { minCgpa: 3.50, label: 'Second Class Honours (Upper Division)', shortLabel: '2:1' },
    { minCgpa: 2.40, label: 'Second Class Honours (Lower Division)', shortLabel: '2:2' },
    { minCgpa: 1.50, label: 'Third Class Honours', shortLabel: '3rd' },
    { minCgpa: 1.00, label: 'Pass', shortLabel: 'Pass' },
    { minCgpa: 0.00, label: 'Fail', shortLabel: 'Fail' },
  ],
  creditSystem: { unit: 'CU', name: 'Credit Unit (NUC)', conversionToECTS: 1.5 },
  academicCalendar: {
    startMonth: 9,
    endMonth: 7,
    semestersPerYear: 2,
    description: 'September – July, two semesters',
  },
  accreditationBodies: ['NUC', 'NBTE', 'AAU', 'CHE (ZA)', 'CUE (Kenya)', 'GTEC (Ghana)'],
  paymentGateways: ['Paystack', 'Flutterwave', 'M-Pesa', 'MTN MoMo', 'Orange Money'],
  complianceFrameworks: ['NDPR (Nigeria)', 'POPIA (South Africa)', 'Kenya DPA'],
  idSchema: [
    { name: 'NIN', pattern: '^[0-9]{11}$' },
    { name: 'Ghana Card' },
    { name: 'SA ID' },
    { name: 'Passport' },
  ],
  theme: {
    primary: '#1a8754',
    secondary: '#d97706',
    accent: '#fbbf24',
    motif: 'kente',
  },
  prayerTimeAware: false,
};
