import type { RegionConfig } from './types';

export const europeConfig: RegionConfig = {
  id: 'europe',
  name: 'Europe',
  shortName: 'EU',
  description: 'Bologna-aligned, ECTS-based, GDPR-compliant for European universities.',
  flagEmoji: '🇪🇺',
  countries: ['United Kingdom', 'Germany', 'France', 'Spain', 'Italy', 'Netherlands', 'Sweden', 'Poland', 'Portugal', 'Ireland', 'Belgium', 'Switzerland'],
  defaultLocale: 'en',
  supportedLocales: ['en', 'fr', 'de', 'es', 'it', 'nl', 'pt', 'pl', 'sv'],
  rtl: false,
  defaultCurrency: 'EUR',
  currencies: ['EUR', 'GBP', 'CHF', 'SEK', 'PLN', 'NOK', 'DKK'],
  defaultTimezone: 'Europe/Brussels',
  dateFormat: 'DD/MM/YYYY',
  numberFormat: 'de-DE',
  nameOrder: 'given-family',
  gpaScaleMax: 4.0,
  gradeScale: [
    { minScore: 90, maxScore: 100, grade: 'A', gradePoint: 4.0, remark: 'Excellent' },
    { minScore: 80, maxScore: 89, grade: 'B', gradePoint: 3.5, remark: 'Very Good' },
    { minScore: 70, maxScore: 79, grade: 'C', gradePoint: 3.0, remark: 'Good' },
    { minScore: 60, maxScore: 69, grade: 'D', gradePoint: 2.5, remark: 'Satisfactory' },
    { minScore: 50, maxScore: 59, grade: 'E', gradePoint: 2.0, remark: 'Sufficient' },
    { minScore: 40, maxScore: 49, grade: 'FX', gradePoint: 1.0, remark: 'Fail (resit allowed)' },
    { minScore: 0, maxScore: 39, grade: 'F', gradePoint: 0.0, remark: 'Fail' },
  ],
  classification: [
    { minCgpa: 3.70, label: 'First Class Honours', shortLabel: 'First' },
    { minCgpa: 3.30, label: 'Upper Second Class Honours', shortLabel: '2:1' },
    { minCgpa: 2.70, label: 'Lower Second Class Honours', shortLabel: '2:2' },
    { minCgpa: 2.00, label: 'Third Class Honours', shortLabel: 'Third' },
    { minCgpa: 1.00, label: 'Pass', shortLabel: 'Pass' },
    { minCgpa: 0.00, label: 'Fail', shortLabel: 'Fail' },
  ],
  creditSystem: { unit: 'ECTS', name: 'European Credit Transfer System', conversionToECTS: 1.0 },
  academicCalendar: {
    startMonth: 9,
    endMonth: 7,
    semestersPerYear: 2,
    description: 'September – July, Bologna-aligned terms',
  },
  accreditationBodies: ['QAA (UK)', 'ENQA', 'AAQ (CH)', 'ANVUR (IT)', 'ANECA (ES)', 'AKKR (DE)'],
  paymentGateways: ['Stripe', 'Mollie', 'Adyen', 'SEPA Direct Debit', 'Klarna'],
  complianceFrameworks: ['GDPR', 'eIDAS', 'Bologna Process', 'ESG Standards'],
  idSchema: [
    { name: 'National ID' },
    { name: 'NIE (Spain)' },
    { name: 'Codice Fiscale (Italy)' },
    { name: 'eIDAS' },
    { name: 'Passport' },
  ],
  theme: {
    primary: '#1e3a8a',
    secondary: '#475569',
    accent: '#facc15',
    motif: 'minimal',
  },
  prayerTimeAware: false,
};
