import type { RegionConfig } from './types';

export const middleEastConfig: RegionConfig = {
  id: 'middleEast',
  name: 'Middle East',
  shortName: 'ME',
  description: 'Tailored for Gulf and Levant universities — NCAAA/CAA-aligned, RTL-ready, prayer-time-aware.',
  flagEmoji: '🕌',
  countries: ['Saudi Arabia', 'United Arab Emirates', 'Qatar', 'Kuwait', 'Bahrain', 'Oman', 'Jordan', 'Lebanon', 'Egypt', 'Israel'],
  defaultLocale: 'ar',
  supportedLocales: ['ar', 'en', 'fr', 'he', 'fa'],
  rtl: true,
  defaultCurrency: 'SAR',
  currencies: ['SAR', 'AED', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'LBP', 'EGP', 'ILS'],
  defaultTimezone: 'Asia/Riyadh',
  dateFormat: 'DD/MM/YYYY',
  numberFormat: 'ar-SA',
  nameOrder: 'patronymic',
  gpaScaleMax: 5.0,
  gradeScale: [
    { minScore: 95, maxScore: 100, grade: 'A+', gradePoint: 5.0, remark: 'Exceptional' },
    { minScore: 90, maxScore: 94, grade: 'A', gradePoint: 4.75, remark: 'Excellent' },
    { minScore: 85, maxScore: 89, grade: 'B+', gradePoint: 4.5, remark: 'Superior' },
    { minScore: 80, maxScore: 84, grade: 'B', gradePoint: 4.0, remark: 'Very Good' },
    { minScore: 75, maxScore: 79, grade: 'C+', gradePoint: 3.5, remark: 'Above Average' },
    { minScore: 70, maxScore: 74, grade: 'C', gradePoint: 3.0, remark: 'Good' },
    { minScore: 65, maxScore: 69, grade: 'D+', gradePoint: 2.5, remark: 'High Pass' },
    { minScore: 60, maxScore: 64, grade: 'D', gradePoint: 2.0, remark: 'Pass' },
    { minScore: 0, maxScore: 59, grade: 'F', gradePoint: 1.0, remark: 'Fail' },
  ],
  classification: [
    { minCgpa: 4.50, label: 'First Honour with Distinction', shortLabel: 'Distinction' },
    { minCgpa: 3.75, label: 'First Honour', shortLabel: 'First Honour' },
    { minCgpa: 2.75, label: 'Second Honour', shortLabel: 'Second Honour' },
    { minCgpa: 2.00, label: 'Pass', shortLabel: 'Pass' },
    { minCgpa: 0.00, label: 'Fail', shortLabel: 'Fail' },
  ],
  creditSystem: { unit: 'SCH', name: 'Semester Credit Hour (NCAAA)', conversionToECTS: 2.0 },
  academicCalendar: {
    startMonth: 9,
    endMonth: 6,
    semestersPerYear: 2,
    description: 'September – June, prayer-time-aware scheduling',
  },
  accreditationBodies: ['NCAAA (KSA)', 'CAA (UAE)', 'OAAA (Oman)', 'EUC (Jordan)', 'CHE (Israel)'],
  paymentGateways: ['HyperPay', 'Payfort', 'Telr', 'PayTabs', 'Stripe'],
  complianceFrameworks: ['PDPL (Saudi Arabia)', 'UAE Federal Data Law', 'ADGM Data Protection'],
  idSchema: [
    { name: 'Iqama' },
    { name: 'Emirates ID' },
    { name: 'Qatar ID' },
    { name: 'Passport' },
  ],
  theme: {
    primary: '#0f766e',
    secondary: '#ca8a04',
    accent: '#d4a017',
    motif: 'arabesque',
  },
  prayerTimeAware: true,
};
