import type { RegionConfig } from './types';

export const northAmericaConfig: RegionConfig = {
  id: 'northAmerica',
  name: 'North America',
  shortName: 'NA',
  description: 'US/Canada-aligned, 4.0 GPA, FERPA/COPPA-compliant.',
  flagEmoji: '🇺🇸',
  countries: ['United States', 'Canada'],
  defaultLocale: 'en',
  supportedLocales: ['en', 'es', 'fr'],
  rtl: false,
  defaultCurrency: 'USD',
  currencies: ['USD', 'CAD'],
  defaultTimezone: 'America/New_York',
  dateFormat: 'MM/DD/YYYY',
  numberFormat: 'en-US',
  nameOrder: 'given-family',
  gpaScaleMax: 4.0,
  gradeScale: [
    { minScore: 93, maxScore: 100, grade: 'A', gradePoint: 4.0, remark: 'Excellent' },
    { minScore: 90, maxScore: 92, grade: 'A-', gradePoint: 3.7, remark: 'Excellent' },
    { minScore: 87, maxScore: 89, grade: 'B+', gradePoint: 3.3, remark: 'Very Good' },
    { minScore: 83, maxScore: 86, grade: 'B', gradePoint: 3.0, remark: 'Good' },
    { minScore: 80, maxScore: 82, grade: 'B-', gradePoint: 2.7, remark: 'Good' },
    { minScore: 77, maxScore: 79, grade: 'C+', gradePoint: 2.3, remark: 'Above Average' },
    { minScore: 73, maxScore: 76, grade: 'C', gradePoint: 2.0, remark: 'Average' },
    { minScore: 70, maxScore: 72, grade: 'C-', gradePoint: 1.7, remark: 'Below Average' },
    { minScore: 67, maxScore: 69, grade: 'D+', gradePoint: 1.3, remark: 'Marginal' },
    { minScore: 63, maxScore: 66, grade: 'D', gradePoint: 1.0, remark: 'Poor' },
    { minScore: 60, maxScore: 62, grade: 'D-', gradePoint: 0.7, remark: 'Very Poor' },
    { minScore: 0, maxScore: 59, grade: 'F', gradePoint: 0.0, remark: 'Fail' },
  ],
  classification: [
    { minCgpa: 3.90, label: 'Summa Cum Laude', shortLabel: 'Summa' },
    { minCgpa: 3.70, label: 'Magna Cum Laude', shortLabel: 'Magna' },
    { minCgpa: 3.50, label: 'Cum Laude', shortLabel: 'Cum Laude' },
    { minCgpa: 2.00, label: 'Pass', shortLabel: 'Pass' },
    { minCgpa: 0.00, label: 'Fail', shortLabel: 'Fail' },
  ],
  creditSystem: { unit: 'CR', name: 'Semester Credit Hour', conversionToECTS: 2.0 },
  academicCalendar: {
    startMonth: 8,
    endMonth: 5,
    semestersPerYear: 2,
    description: 'August – May, Fall and Spring semesters',
  },
  accreditationBodies: ['SACSCOC', 'WASC', 'HLC', 'MSCHE', 'NEASC', 'NWCCU'],
  paymentGateways: ['Stripe', 'Plaid', 'ACH', 'PayPal', 'Apple Pay'],
  complianceFrameworks: ['FERPA', 'HIPAA', 'COPPA', 'CCPA', 'PIPEDA (Canada)'],
  idSchema: [
    { name: 'SSN (last 4)' },
    { name: 'SIN (Canada)' },
    { name: 'Passport' },
    { name: 'Driver License' },
  ],
  theme: {
    primary: '#1e40af',
    secondary: '#b91c1c',
    accent: '#f59e0b',
    motif: 'collegiate',
  },
  prayerTimeAware: false,
};
